version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./src/main/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: dasdjhqwgejhasbdi
      MYSQL_DATABASE: carapi
      MYSQL_USER: carapi_user
      MYSQL_PASSWORD: carapi123456789

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: carapi_user
      DB_PASSWORD: carapi123456789
      DB_PORT: 3306